package com.weichat.boss.data.dao;

import com.weichat.boss.data.pojo.ExpertReview;
import com.weichat.boss.data.pojo.ExpertReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpertReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int countByExample(ExpertReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int deleteByExample(ExpertReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int insert(ExpertReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int insertSelective(ExpertReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    List<ExpertReview> selectByExample(ExpertReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    ExpertReview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int updateByExampleSelective(@Param("record") ExpertReview record, @Param("example") ExpertReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int updateByExample(@Param("record") ExpertReview record, @Param("example") ExpertReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int updateByPrimaryKeySelective(ExpertReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_review
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    int updateByPrimaryKey(ExpertReview record);
}