package com.weichat.boss.data.dao;

import com.weichat.boss.data.pojo.VoteRecord;
import com.weichat.boss.data.pojo.VoteRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int countByExample(VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int deleteByExample(VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int insert(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int insertSelective(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    List<VoteRecord> selectByExample(VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    VoteRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int updateByExampleSelective(@Param("record") VoteRecord record, @Param("example") VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int updateByExample(@Param("record") VoteRecord record, @Param("example") VoteRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int updateByPrimaryKeySelective(VoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_record
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    int updateByPrimaryKey(VoteRecord record);
}