package com.weichat.boss.data.pojo;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.id
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.name
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.customerId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.accessCmd
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String accesscmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.accessUrl
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String accessurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.type
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.createtime
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.status
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.backup1
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.backup2
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.backup3
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.backup4
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.id
     *
     * @return the value of t_channel.id
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.id
     *
     * @param id the value for t_channel.id
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.name
     *
     * @return the value of t_channel.name
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.name
     *
     * @param name the value for t_channel.name
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.customerId
     *
     * @return the value of t_channel.customerId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.customerId
     *
     * @param customerid the value for t_channel.customerId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.accessCmd
     *
     * @return the value of t_channel.accessCmd
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getAccesscmd() {
        return accesscmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.accessCmd
     *
     * @param accesscmd the value for t_channel.accessCmd
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setAccesscmd(String accesscmd) {
        this.accesscmd = accesscmd == null ? null : accesscmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.accessUrl
     *
     * @return the value of t_channel.accessUrl
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getAccessurl() {
        return accessurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.accessUrl
     *
     * @param accessurl the value for t_channel.accessUrl
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setAccessurl(String accessurl) {
        this.accessurl = accessurl == null ? null : accessurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.type
     *
     * @return the value of t_channel.type
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.type
     *
     * @param type the value for t_channel.type
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.createtime
     *
     * @return the value of t_channel.createtime
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.createtime
     *
     * @param createtime the value for t_channel.createtime
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.status
     *
     * @return the value of t_channel.status
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.status
     *
     * @param status the value for t_channel.status
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.backup1
     *
     * @return the value of t_channel.backup1
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.backup1
     *
     * @param backup1 the value for t_channel.backup1
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.backup2
     *
     * @return the value of t_channel.backup2
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.backup2
     *
     * @param backup2 the value for t_channel.backup2
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.backup3
     *
     * @return the value of t_channel.backup3
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.backup3
     *
     * @param backup3 the value for t_channel.backup3
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.backup4
     *
     * @return the value of t_channel.backup4
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup4() {
        return backup4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.backup4
     *
     * @param backup4 the value for t_channel.backup4
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup4(String backup4) {
        this.backup4 = backup4 == null ? null : backup4.trim();
    }
}