package com.weichat.boss.data.pojo;

public class CustomerAlbumPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.id
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.customerId
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.albumId
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private Integer albumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.photoName
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String photoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.photoSummary
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String photosummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.saveFile
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String savefile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.createtime
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.backup1
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.backup2
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.backup3
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_album_photo.backup4
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    private String backup4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.id
     *
     * @return the value of t_customer_album_photo.id
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.id
     *
     * @param id the value for t_customer_album_photo.id
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.customerId
     *
     * @return the value of t_customer_album_photo.customerId
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.customerId
     *
     * @param customerid the value for t_customer_album_photo.customerId
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.albumId
     *
     * @return the value of t_customer_album_photo.albumId
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public Integer getAlbumid() {
        return albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.albumId
     *
     * @param albumid the value for t_customer_album_photo.albumId
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setAlbumid(Integer albumid) {
        this.albumid = albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.photoName
     *
     * @return the value of t_customer_album_photo.photoName
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getPhotoname() {
        return photoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.photoName
     *
     * @param photoname the value for t_customer_album_photo.photoName
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setPhotoname(String photoname) {
        this.photoname = photoname == null ? null : photoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.photoSummary
     *
     * @return the value of t_customer_album_photo.photoSummary
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getPhotosummary() {
        return photosummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.photoSummary
     *
     * @param photosummary the value for t_customer_album_photo.photoSummary
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setPhotosummary(String photosummary) {
        this.photosummary = photosummary == null ? null : photosummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.saveFile
     *
     * @return the value of t_customer_album_photo.saveFile
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getSavefile() {
        return savefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.saveFile
     *
     * @param savefile the value for t_customer_album_photo.saveFile
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setSavefile(String savefile) {
        this.savefile = savefile == null ? null : savefile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.createtime
     *
     * @return the value of t_customer_album_photo.createtime
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.createtime
     *
     * @param createtime the value for t_customer_album_photo.createtime
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.backup1
     *
     * @return the value of t_customer_album_photo.backup1
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.backup1
     *
     * @param backup1 the value for t_customer_album_photo.backup1
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.backup2
     *
     * @return the value of t_customer_album_photo.backup2
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.backup2
     *
     * @param backup2 the value for t_customer_album_photo.backup2
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.backup3
     *
     * @return the value of t_customer_album_photo.backup3
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.backup3
     *
     * @param backup3 the value for t_customer_album_photo.backup3
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_album_photo.backup4
     *
     * @return the value of t_customer_album_photo.backup4
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public String getBackup4() {
        return backup4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_album_photo.backup4
     *
     * @param backup4 the value for t_customer_album_photo.backup4
     *
     * @mbggenerated Sun Jun 30 18:33:31 CST 2013
     */
    public void setBackup4(String backup4) {
        this.backup4 = backup4 == null ? null : backup4.trim();
    }
}