package com.weichat.boss.data.pojo;

import java.util.ArrayList;
import java.util.List;

public class CustomerAlbumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public CustomerAlbumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNull() {
            addCriterion("customerId is null");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNotNull() {
            addCriterion("customerId is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeridEqualTo(String value) {
            addCriterion("customerId =", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotEqualTo(String value) {
            addCriterion("customerId <>", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThan(String value) {
            addCriterion("customerId >", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThanOrEqualTo(String value) {
            addCriterion("customerId >=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThan(String value) {
            addCriterion("customerId <", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThanOrEqualTo(String value) {
            addCriterion("customerId <=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLike(String value) {
            addCriterion("customerId like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotLike(String value) {
            addCriterion("customerId not like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIn(List<String> values) {
            addCriterion("customerId in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotIn(List<String> values) {
            addCriterion("customerId not in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridBetween(String value1, String value2) {
            addCriterion("customerId between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotBetween(String value1, String value2) {
            addCriterion("customerId not between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andAlbumnameIsNull() {
            addCriterion("albumName is null");
            return (Criteria) this;
        }

        public Criteria andAlbumnameIsNotNull() {
            addCriterion("albumName is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumnameEqualTo(String value) {
            addCriterion("albumName =", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameNotEqualTo(String value) {
            addCriterion("albumName <>", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameGreaterThan(String value) {
            addCriterion("albumName >", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameGreaterThanOrEqualTo(String value) {
            addCriterion("albumName >=", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameLessThan(String value) {
            addCriterion("albumName <", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameLessThanOrEqualTo(String value) {
            addCriterion("albumName <=", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameLike(String value) {
            addCriterion("albumName like", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameNotLike(String value) {
            addCriterion("albumName not like", value, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameIn(List<String> values) {
            addCriterion("albumName in", values, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameNotIn(List<String> values) {
            addCriterion("albumName not in", values, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameBetween(String value1, String value2) {
            addCriterion("albumName between", value1, value2, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumnameNotBetween(String value1, String value2) {
            addCriterion("albumName not between", value1, value2, "albumname");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryIsNull() {
            addCriterion("albumSummary is null");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryIsNotNull() {
            addCriterion("albumSummary is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryEqualTo(String value) {
            addCriterion("albumSummary =", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryNotEqualTo(String value) {
            addCriterion("albumSummary <>", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryGreaterThan(String value) {
            addCriterion("albumSummary >", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryGreaterThanOrEqualTo(String value) {
            addCriterion("albumSummary >=", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryLessThan(String value) {
            addCriterion("albumSummary <", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryLessThanOrEqualTo(String value) {
            addCriterion("albumSummary <=", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryLike(String value) {
            addCriterion("albumSummary like", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryNotLike(String value) {
            addCriterion("albumSummary not like", value, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryIn(List<String> values) {
            addCriterion("albumSummary in", values, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryNotIn(List<String> values) {
            addCriterion("albumSummary not in", values, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryBetween(String value1, String value2) {
            addCriterion("albumSummary between", value1, value2, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumsummaryNotBetween(String value1, String value2) {
            addCriterion("albumSummary not between", value1, value2, "albumsummary");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorIsNull() {
            addCriterion("albumAuthor is null");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorIsNotNull() {
            addCriterion("albumAuthor is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorEqualTo(String value) {
            addCriterion("albumAuthor =", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorNotEqualTo(String value) {
            addCriterion("albumAuthor <>", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorGreaterThan(String value) {
            addCriterion("albumAuthor >", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorGreaterThanOrEqualTo(String value) {
            addCriterion("albumAuthor >=", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorLessThan(String value) {
            addCriterion("albumAuthor <", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorLessThanOrEqualTo(String value) {
            addCriterion("albumAuthor <=", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorLike(String value) {
            addCriterion("albumAuthor like", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorNotLike(String value) {
            addCriterion("albumAuthor not like", value, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorIn(List<String> values) {
            addCriterion("albumAuthor in", values, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorNotIn(List<String> values) {
            addCriterion("albumAuthor not in", values, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorBetween(String value1, String value2) {
            addCriterion("albumAuthor between", value1, value2, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andAlbumauthorNotBetween(String value1, String value2) {
            addCriterion("albumAuthor not between", value1, value2, "albumauthor");
            return (Criteria) this;
        }

        public Criteria andShoottimeIsNull() {
            addCriterion("shootTime is null");
            return (Criteria) this;
        }

        public Criteria andShoottimeIsNotNull() {
            addCriterion("shootTime is not null");
            return (Criteria) this;
        }

        public Criteria andShoottimeEqualTo(String value) {
            addCriterion("shootTime =", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeNotEqualTo(String value) {
            addCriterion("shootTime <>", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeGreaterThan(String value) {
            addCriterion("shootTime >", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeGreaterThanOrEqualTo(String value) {
            addCriterion("shootTime >=", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeLessThan(String value) {
            addCriterion("shootTime <", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeLessThanOrEqualTo(String value) {
            addCriterion("shootTime <=", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeLike(String value) {
            addCriterion("shootTime like", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeNotLike(String value) {
            addCriterion("shootTime not like", value, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeIn(List<String> values) {
            addCriterion("shootTime in", values, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeNotIn(List<String> values) {
            addCriterion("shootTime not in", values, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeBetween(String value1, String value2) {
            addCriterion("shootTime between", value1, value2, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShoottimeNotBetween(String value1, String value2) {
            addCriterion("shootTime not between", value1, value2, "shoottime");
            return (Criteria) this;
        }

        public Criteria andShootaddressIsNull() {
            addCriterion("shootAddress is null");
            return (Criteria) this;
        }

        public Criteria andShootaddressIsNotNull() {
            addCriterion("shootAddress is not null");
            return (Criteria) this;
        }

        public Criteria andShootaddressEqualTo(String value) {
            addCriterion("shootAddress =", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressNotEqualTo(String value) {
            addCriterion("shootAddress <>", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressGreaterThan(String value) {
            addCriterion("shootAddress >", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressGreaterThanOrEqualTo(String value) {
            addCriterion("shootAddress >=", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressLessThan(String value) {
            addCriterion("shootAddress <", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressLessThanOrEqualTo(String value) {
            addCriterion("shootAddress <=", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressLike(String value) {
            addCriterion("shootAddress like", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressNotLike(String value) {
            addCriterion("shootAddress not like", value, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressIn(List<String> values) {
            addCriterion("shootAddress in", values, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressNotIn(List<String> values) {
            addCriterion("shootAddress not in", values, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressBetween(String value1, String value2) {
            addCriterion("shootAddress between", value1, value2, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andShootaddressNotBetween(String value1, String value2) {
            addCriterion("shootAddress not between", value1, value2, "shootaddress");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleIsNull() {
            addCriterion("albumStyle is null");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleIsNotNull() {
            addCriterion("albumStyle is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleEqualTo(String value) {
            addCriterion("albumStyle =", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleNotEqualTo(String value) {
            addCriterion("albumStyle <>", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleGreaterThan(String value) {
            addCriterion("albumStyle >", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleGreaterThanOrEqualTo(String value) {
            addCriterion("albumStyle >=", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleLessThan(String value) {
            addCriterion("albumStyle <", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleLessThanOrEqualTo(String value) {
            addCriterion("albumStyle <=", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleLike(String value) {
            addCriterion("albumStyle like", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleNotLike(String value) {
            addCriterion("albumStyle not like", value, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleIn(List<String> values) {
            addCriterion("albumStyle in", values, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleNotIn(List<String> values) {
            addCriterion("albumStyle not in", values, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleBetween(String value1, String value2) {
            addCriterion("albumStyle between", value1, value2, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andAlbumstyleNotBetween(String value1, String value2) {
            addCriterion("albumStyle not between", value1, value2, "albumstyle");
            return (Criteria) this;
        }

        public Criteria andSavepathIsNull() {
            addCriterion("savePath is null");
            return (Criteria) this;
        }

        public Criteria andSavepathIsNotNull() {
            addCriterion("savePath is not null");
            return (Criteria) this;
        }

        public Criteria andSavepathEqualTo(String value) {
            addCriterion("savePath =", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotEqualTo(String value) {
            addCriterion("savePath <>", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathGreaterThan(String value) {
            addCriterion("savePath >", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathGreaterThanOrEqualTo(String value) {
            addCriterion("savePath >=", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathLessThan(String value) {
            addCriterion("savePath <", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathLessThanOrEqualTo(String value) {
            addCriterion("savePath <=", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathLike(String value) {
            addCriterion("savePath like", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotLike(String value) {
            addCriterion("savePath not like", value, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathIn(List<String> values) {
            addCriterion("savePath in", values, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotIn(List<String> values) {
            addCriterion("savePath not in", values, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathBetween(String value1, String value2) {
            addCriterion("savePath between", value1, value2, "savepath");
            return (Criteria) this;
        }

        public Criteria andSavepathNotBetween(String value1, String value2) {
            addCriterion("savePath not between", value1, value2, "savepath");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("createTime like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("createTime not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andBackup1IsNull() {
            addCriterion("backup1 is null");
            return (Criteria) this;
        }

        public Criteria andBackup1IsNotNull() {
            addCriterion("backup1 is not null");
            return (Criteria) this;
        }

        public Criteria andBackup1EqualTo(String value) {
            addCriterion("backup1 =", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1NotEqualTo(String value) {
            addCriterion("backup1 <>", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1GreaterThan(String value) {
            addCriterion("backup1 >", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1GreaterThanOrEqualTo(String value) {
            addCriterion("backup1 >=", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1LessThan(String value) {
            addCriterion("backup1 <", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1LessThanOrEqualTo(String value) {
            addCriterion("backup1 <=", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1Like(String value) {
            addCriterion("backup1 like", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1NotLike(String value) {
            addCriterion("backup1 not like", value, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1In(List<String> values) {
            addCriterion("backup1 in", values, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1NotIn(List<String> values) {
            addCriterion("backup1 not in", values, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1Between(String value1, String value2) {
            addCriterion("backup1 between", value1, value2, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup1NotBetween(String value1, String value2) {
            addCriterion("backup1 not between", value1, value2, "backup1");
            return (Criteria) this;
        }

        public Criteria andBackup2IsNull() {
            addCriterion("backup2 is null");
            return (Criteria) this;
        }

        public Criteria andBackup2IsNotNull() {
            addCriterion("backup2 is not null");
            return (Criteria) this;
        }

        public Criteria andBackup2EqualTo(String value) {
            addCriterion("backup2 =", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2NotEqualTo(String value) {
            addCriterion("backup2 <>", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2GreaterThan(String value) {
            addCriterion("backup2 >", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2GreaterThanOrEqualTo(String value) {
            addCriterion("backup2 >=", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2LessThan(String value) {
            addCriterion("backup2 <", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2LessThanOrEqualTo(String value) {
            addCriterion("backup2 <=", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2Like(String value) {
            addCriterion("backup2 like", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2NotLike(String value) {
            addCriterion("backup2 not like", value, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2In(List<String> values) {
            addCriterion("backup2 in", values, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2NotIn(List<String> values) {
            addCriterion("backup2 not in", values, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2Between(String value1, String value2) {
            addCriterion("backup2 between", value1, value2, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup2NotBetween(String value1, String value2) {
            addCriterion("backup2 not between", value1, value2, "backup2");
            return (Criteria) this;
        }

        public Criteria andBackup3IsNull() {
            addCriterion("backup3 is null");
            return (Criteria) this;
        }

        public Criteria andBackup3IsNotNull() {
            addCriterion("backup3 is not null");
            return (Criteria) this;
        }

        public Criteria andBackup3EqualTo(String value) {
            addCriterion("backup3 =", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3NotEqualTo(String value) {
            addCriterion("backup3 <>", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3GreaterThan(String value) {
            addCriterion("backup3 >", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3GreaterThanOrEqualTo(String value) {
            addCriterion("backup3 >=", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3LessThan(String value) {
            addCriterion("backup3 <", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3LessThanOrEqualTo(String value) {
            addCriterion("backup3 <=", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3Like(String value) {
            addCriterion("backup3 like", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3NotLike(String value) {
            addCriterion("backup3 not like", value, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3In(List<String> values) {
            addCriterion("backup3 in", values, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3NotIn(List<String> values) {
            addCriterion("backup3 not in", values, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3Between(String value1, String value2) {
            addCriterion("backup3 between", value1, value2, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup3NotBetween(String value1, String value2) {
            addCriterion("backup3 not between", value1, value2, "backup3");
            return (Criteria) this;
        }

        public Criteria andBackup4IsNull() {
            addCriterion("backup4 is null");
            return (Criteria) this;
        }

        public Criteria andBackup4IsNotNull() {
            addCriterion("backup4 is not null");
            return (Criteria) this;
        }

        public Criteria andBackup4EqualTo(String value) {
            addCriterion("backup4 =", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4NotEqualTo(String value) {
            addCriterion("backup4 <>", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4GreaterThan(String value) {
            addCriterion("backup4 >", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4GreaterThanOrEqualTo(String value) {
            addCriterion("backup4 >=", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4LessThan(String value) {
            addCriterion("backup4 <", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4LessThanOrEqualTo(String value) {
            addCriterion("backup4 <=", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4Like(String value) {
            addCriterion("backup4 like", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4NotLike(String value) {
            addCriterion("backup4 not like", value, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4In(List<String> values) {
            addCriterion("backup4 in", values, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4NotIn(List<String> values) {
            addCriterion("backup4 not in", values, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4Between(String value1, String value2) {
            addCriterion("backup4 between", value1, value2, "backup4");
            return (Criteria) this;
        }

        public Criteria andBackup4NotBetween(String value1, String value2) {
            addCriterion("backup4 not between", value1, value2, "backup4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer_album
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 27 21:21:56 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer_album
     *
     * @mbggenerated Thu Jun 27 21:21:56 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}