package com.weichat.boss.data.pojo;

public class ExpertReview {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.id
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.name
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.headSculpture
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String headsculpture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.title
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.honor
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String honor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.reviewSubject
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String reviewsubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.reviewContent
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String reviewcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.customerId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.templateId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.templateAreaId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private Integer templateareaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.backup1
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.backup2
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.backup3
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_review.backup4
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    private String backup4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.id
     *
     * @return the value of t_expert_review.id
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.id
     *
     * @param id the value for t_expert_review.id
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.name
     *
     * @return the value of t_expert_review.name
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.name
     *
     * @param name the value for t_expert_review.name
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.headSculpture
     *
     * @return the value of t_expert_review.headSculpture
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getHeadsculpture() {
        return headsculpture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.headSculpture
     *
     * @param headsculpture the value for t_expert_review.headSculpture
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setHeadsculpture(String headsculpture) {
        this.headsculpture = headsculpture == null ? null : headsculpture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.title
     *
     * @return the value of t_expert_review.title
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.title
     *
     * @param title the value for t_expert_review.title
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.honor
     *
     * @return the value of t_expert_review.honor
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.honor
     *
     * @param honor the value for t_expert_review.honor
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.reviewSubject
     *
     * @return the value of t_expert_review.reviewSubject
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getReviewsubject() {
        return reviewsubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.reviewSubject
     *
     * @param reviewsubject the value for t_expert_review.reviewSubject
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setReviewsubject(String reviewsubject) {
        this.reviewsubject = reviewsubject == null ? null : reviewsubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.reviewContent
     *
     * @return the value of t_expert_review.reviewContent
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getReviewcontent() {
        return reviewcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.reviewContent
     *
     * @param reviewcontent the value for t_expert_review.reviewContent
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setReviewcontent(String reviewcontent) {
        this.reviewcontent = reviewcontent == null ? null : reviewcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.customerId
     *
     * @return the value of t_expert_review.customerId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.customerId
     *
     * @param customerid the value for t_expert_review.customerId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.templateId
     *
     * @return the value of t_expert_review.templateId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.templateId
     *
     * @param templateid the value for t_expert_review.templateId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.templateAreaId
     *
     * @return the value of t_expert_review.templateAreaId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public Integer getTemplateareaid() {
        return templateareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.templateAreaId
     *
     * @param templateareaid the value for t_expert_review.templateAreaId
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setTemplateareaid(Integer templateareaid) {
        this.templateareaid = templateareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.backup1
     *
     * @return the value of t_expert_review.backup1
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.backup1
     *
     * @param backup1 the value for t_expert_review.backup1
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.backup2
     *
     * @return the value of t_expert_review.backup2
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.backup2
     *
     * @param backup2 the value for t_expert_review.backup2
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.backup3
     *
     * @return the value of t_expert_review.backup3
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.backup3
     *
     * @param backup3 the value for t_expert_review.backup3
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_review.backup4
     *
     * @return the value of t_expert_review.backup4
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public String getBackup4() {
        return backup4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_review.backup4
     *
     * @param backup4 the value for t_expert_review.backup4
     *
     * @mbggenerated Tue Jul 02 21:51:21 CST 2013
     */
    public void setBackup4(String backup4) {
        this.backup4 = backup4 == null ? null : backup4.trim();
    }
}