package com.weichat.boss.data.pojo;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.id
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.name
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.showName
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer showname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.sequence
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.status
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.channelId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.customerId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.createtime
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.backup1
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.backup2
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.backup3
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.backup4
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String backup4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.type
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.summary
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.showSummary
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    private Integer showsummary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.id
     *
     * @return the value of t_module.id
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.id
     *
     * @param id the value for t_module.id
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.name
     *
     * @return the value of t_module.name
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.name
     *
     * @param name the value for t_module.name
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.showName
     *
     * @return the value of t_module.showName
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getShowname() {
        return showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.showName
     *
     * @param showname the value for t_module.showName
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setShowname(Integer showname) {
        this.showname = showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.sequence
     *
     * @return the value of t_module.sequence
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.sequence
     *
     * @param sequence the value for t_module.sequence
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.status
     *
     * @return the value of t_module.status
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.status
     *
     * @param status the value for t_module.status
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.channelId
     *
     * @return the value of t_module.channelId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.channelId
     *
     * @param channelid the value for t_module.channelId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setChannelid(Integer channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.customerId
     *
     * @return the value of t_module.customerId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.customerId
     *
     * @param customerid the value for t_module.customerId
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.createtime
     *
     * @return the value of t_module.createtime
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.createtime
     *
     * @param createtime the value for t_module.createtime
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.backup1
     *
     * @return the value of t_module.backup1
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.backup1
     *
     * @param backup1 the value for t_module.backup1
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.backup2
     *
     * @return the value of t_module.backup2
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.backup2
     *
     * @param backup2 the value for t_module.backup2
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.backup3
     *
     * @return the value of t_module.backup3
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.backup3
     *
     * @param backup3 the value for t_module.backup3
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.backup4
     *
     * @return the value of t_module.backup4
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getBackup4() {
        return backup4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.backup4
     *
     * @param backup4 the value for t_module.backup4
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setBackup4(String backup4) {
        this.backup4 = backup4 == null ? null : backup4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.type
     *
     * @return the value of t_module.type
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.type
     *
     * @param type the value for t_module.type
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.summary
     *
     * @return the value of t_module.summary
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.summary
     *
     * @param summary the value for t_module.summary
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.showSummary
     *
     * @return the value of t_module.showSummary
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public Integer getShowsummary() {
        return showsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.showSummary
     *
     * @param showsummary the value for t_module.showSummary
     *
     * @mbggenerated Mon Jun 17 23:27:58 CST 2013
     */
    public void setShowsummary(Integer showsummary) {
        this.showsummary = showsummary;
    }
}