package com.weichat.boss.data.pojo;

public class Template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.id
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.name
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.type
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.summary
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.areaNum
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private Integer areanum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.backup1
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.backup2
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.backup3
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.backup4
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String backup4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.addtime
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    private String addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.id
     *
     * @return the value of t_template.id
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.id
     *
     * @param id the value for t_template.id
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.name
     *
     * @return the value of t_template.name
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.name
     *
     * @param name the value for t_template.name
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.type
     *
     * @return the value of t_template.type
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.type
     *
     * @param type the value for t_template.type
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.summary
     *
     * @return the value of t_template.summary
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.summary
     *
     * @param summary the value for t_template.summary
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.areaNum
     *
     * @return the value of t_template.areaNum
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public Integer getAreanum() {
        return areanum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.areaNum
     *
     * @param areanum the value for t_template.areaNum
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setAreanum(Integer areanum) {
        this.areanum = areanum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.backup1
     *
     * @return the value of t_template.backup1
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.backup1
     *
     * @param backup1 the value for t_template.backup1
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.backup2
     *
     * @return the value of t_template.backup2
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.backup2
     *
     * @param backup2 the value for t_template.backup2
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.backup3
     *
     * @return the value of t_template.backup3
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.backup3
     *
     * @param backup3 the value for t_template.backup3
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.backup4
     *
     * @return the value of t_template.backup4
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getBackup4() {
        return backup4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.backup4
     *
     * @param backup4 the value for t_template.backup4
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setBackup4(String backup4) {
        this.backup4 = backup4 == null ? null : backup4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.addtime
     *
     * @return the value of t_template.addtime
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.addtime
     *
     * @param addtime the value for t_template.addtime
     *
     * @mbggenerated Sun Jun 30 15:04:54 CST 2013
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime == null ? null : addtime.trim();
    }
}