package com.weichat.boss.data.pojo;

public class VoteRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.id
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.voteId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.voteOptionId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer voteoptionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.userId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.voteTime
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String votetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.backup1
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.backup2
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.backup3
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_record.backup4
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.id
     *
     * @return the value of t_vote_record.id
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.id
     *
     * @param id the value for t_vote_record.id
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.voteId
     *
     * @return the value of t_vote_record.voteId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.voteId
     *
     * @param voteid the value for t_vote_record.voteId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setVoteid(Integer voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.voteOptionId
     *
     * @return the value of t_vote_record.voteOptionId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getVoteoptionid() {
        return voteoptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.voteOptionId
     *
     * @param voteoptionid the value for t_vote_record.voteOptionId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setVoteoptionid(Integer voteoptionid) {
        this.voteoptionid = voteoptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.userId
     *
     * @return the value of t_vote_record.userId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.userId
     *
     * @param userid the value for t_vote_record.userId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.voteTime
     *
     * @return the value of t_vote_record.voteTime
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getVotetime() {
        return votetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.voteTime
     *
     * @param votetime the value for t_vote_record.voteTime
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setVotetime(String votetime) {
        this.votetime = votetime == null ? null : votetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.backup1
     *
     * @return the value of t_vote_record.backup1
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.backup1
     *
     * @param backup1 the value for t_vote_record.backup1
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.backup2
     *
     * @return the value of t_vote_record.backup2
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.backup2
     *
     * @param backup2 the value for t_vote_record.backup2
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.backup3
     *
     * @return the value of t_vote_record.backup3
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.backup3
     *
     * @param backup3 the value for t_vote_record.backup3
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_record.backup4
     *
     * @return the value of t_vote_record.backup4
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup4() {
        return backup4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_record.backup4
     *
     * @param backup4 the value for t_vote_record.backup4
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup4(String backup4) {
        this.backup4 = backup4 == null ? null : backup4.trim();
    }
}