package com.weichat.boss.data.pojo;

public class VoteOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.id
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.customerId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.templateId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.templateAreaId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer templateareaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.voteId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.name
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.votes
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private Integer votes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.backup1
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.backup2
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.backup3
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_option.backup4
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    private String backup4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.id
     *
     * @return the value of t_vote_option.id
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.id
     *
     * @param id the value for t_vote_option.id
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.customerId
     *
     * @return the value of t_vote_option.customerId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.customerId
     *
     * @param customerid the value for t_vote_option.customerId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.templateId
     *
     * @return the value of t_vote_option.templateId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.templateId
     *
     * @param templateid the value for t_vote_option.templateId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.templateAreaId
     *
     * @return the value of t_vote_option.templateAreaId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getTemplateareaid() {
        return templateareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.templateAreaId
     *
     * @param templateareaid the value for t_vote_option.templateAreaId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setTemplateareaid(Integer templateareaid) {
        this.templateareaid = templateareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.voteId
     *
     * @return the value of t_vote_option.voteId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.voteId
     *
     * @param voteid the value for t_vote_option.voteId
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setVoteid(Integer voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.name
     *
     * @return the value of t_vote_option.name
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.name
     *
     * @param name the value for t_vote_option.name
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.votes
     *
     * @return the value of t_vote_option.votes
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public Integer getVotes() {
        return votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.votes
     *
     * @param votes the value for t_vote_option.votes
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.backup1
     *
     * @return the value of t_vote_option.backup1
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.backup1
     *
     * @param backup1 the value for t_vote_option.backup1
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.backup2
     *
     * @return the value of t_vote_option.backup2
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.backup2
     *
     * @param backup2 the value for t_vote_option.backup2
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.backup3
     *
     * @return the value of t_vote_option.backup3
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.backup3
     *
     * @param backup3 the value for t_vote_option.backup3
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_option.backup4
     *
     * @return the value of t_vote_option.backup4
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public String getBackup4() {
        return backup4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_option.backup4
     *
     * @param backup4 the value for t_vote_option.backup4
     *
     * @mbggenerated Tue Jul 02 21:21:17 CST 2013
     */
    public void setBackup4(String backup4) {
        this.backup4 = backup4 == null ? null : backup4.trim();
    }
}